name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-instance1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run first vECU instance at SILKIT local host and port 8500
        shell: powershell
        run: C:/PND/Visit/MAM/LightControl_StandaloneSUT/SUT/Run_Setup.bat

      - name: Run first instance of CANoe4SWSE at SILKIT local host and port 8500 to test first instance of vECU
        shell: powershell
        run: C:/PND/Visit/MAM/LightControl_StandaloneSUT/CANoe_StandaloneSUT/run_final.ps1

  build-instance2:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run Second vECU instance at SILKIT local host and port 8501
        shell: powershell
        run: C:/PND/Visit/MAM/LightControl_StandaloneSUT_Instance2/SUT/Run_Setup.bat

      - name: Run second instance of CANoe4SWSE at SILKIT local host and port 8501 to test Second instance of vECU
        shell: powershell
        run: C:/PND/Visit/MAM/LightControl_StandaloneSUT_Instance2/CANoe_StandaloneSUT/run_final.ps1
