# This is a basic workflow to help you get started with Actions 

 

name: CI 

 

# Controls when the workflow will run 

on: 

  # Triggers the workflow on push or pull request events but only for the "main" branch 

  push: 

    branches: [ "main" ] 

  pull_request: 

    branches: [ "main" ] 

 

  # Allows you to run this workflow manually from the Actions tab 

  workflow_dispatch: 

 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 

jobs: 

  # This workflow contains a single job called "build" 

  build: 

    # The type of runner that the job will run on 

    runs-on: self-hosted

 

    # Steps represent a sequence of tasks that will be executed as part of the job 

    steps: 

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 

      - uses: actions/checkout@v4 

      # Runs a single command using the runners shell 

      - name: Run first vECU instance at SILKIT local host and port 8500 

        shell: powershell 

        run: C:/PND/Visit/MAM/LightControl_StandaloneSUT/SUT/Run_Setup.bat

      - name: Run Second vECU instance at SILKIT local host and port 8501 
        shell: powershell
        run: C:/PND/Visit/MAM/LightControl_StandaloneSUT_Instance2/SUT/Run_Setup.bat


      - name: Run first instance of CANoe4SWSE at SILKIT local host and port 8500 to test first instance of vECU 
        shell: powershell
        run: C:/PND/Visit/MAM/LightControl_StandaloneSUT/CANoe_StandaloneSUT/run_final.ps1             

      - name: Run second instance of CANoe4SWSE at SILKIT local host and port 8501 to test Second instance of vECU 
        shell: powershell
        run: C:/PND/Visit/MAM/LightControl_StandaloneSUT_Instance2/CANoe_StandaloneSUT/run_final.ps1 
